### PR TITLE
I18N

### PR DESCRIPTION
**Pull request by RedFraction**
As I promised, a new format for changing languages, with everything you asked for. Sorry for possible waiting, too much work and releases at other projects.

### CODE REVIEW

**Comment by RedFraction** [comment]
Does U checked?

**Comment by kanehekili** [comment]
Sorry, I haven't got the time currently, but your work is impressive. 
Did you find the texts by hand or do you have some kind of software parsing the code that needs to be translated?

**Comment by RedFraction** [comment]
All of text dictionaries was translated by myself.

**Comment by RedFraction** [comment]
Does u checked?

**Comment by kanehekili** [comment]
Sorry, I really appreciate your help. Currently, I have a deadline with my TSVAccess project. After that, I am looking for a solution that parses the code, not setting it up manually. The reason: If I continue changing the code, I just want to process it, not marking it by hand.

**Comment by kanehekili** [comment]
Currently I do not support any request from Russia. From my point of view Russia tries to invade a country that doesn't belong to you. No matter what your  official media says, I'm not going support any Russian aggression towards any country that decides **NOT** be part of another country.

**Comment by RedFraction** [comment]
1. I'm not living in Russia about 2 years
2. Open-source should be out of politics
3. Thanks for your honest

**Comment by RedFraction** [comment]
It’s very convenient to be against war, but at the same time to incite it by yourself, isn’t it?

**Comment by kanehekili** [comment]
I was in jail because I didn't go to the (compulsory) army in the 1980 years.. . Probably, we're both on the same side. Did not mean to hurt you, so I apologize..

**Pull request closed without merging**
