### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by RedFraction**
- Edit i8n native naming
- Added new icons (hand drawn)

### CODE REVIEW

**Comment by RedFraction** [comment]
Icons drawed by me

**Comment by RedFraction** [comment]
Need review for I8N module, cause it's my first time writing something in Python.

**Comment by kanehekili** [comment]
thanks for providing the pull request. I'll check your src/I8N.py.
Concerning the icons - since I do not want to miss my colorful icons, i'd like to have the icons in a separate folder.
(eg colorIcons and flatIcons) The icons in each folder should have the same name. So in code we can switch easily from one "iconset" to another. I'll provide an additional setting for selecting the icons.

**Comment by kanehekili** [comment]
Screenshot for dark themes: That won't work
image

So we would need either two "iconthemes" from you, or your icons are agnostic to "light" or "dark" mode.
I Like your multi language approach, but you did not consider the other modules. Can you give me a hint how you created them ? (Ihaven't used I8N yet, but this looks cool) . Having just one file makes language support a little more difficult  (against the standard python NLS, which has a .po file for every language...). Check the offical [documentation](https://docs.python.org/3/library/i18n.html) using "gettext"

**Comment by kanehekili** [comment]
After reading some more stuff I'm inclined to reject your pull request concerning I8N. If you use "gettext", I will support you fully.  If you could update your pullrequest with the "gettext" module I 'll support it. - And thanks for help!

**Comment by RedFraction** [comment]
R U sure, that U want to use gettext? It's more complicated than my solution, but wokrs similary. I think that JSON format more human-friendly than ".po".

**Comment by kanehekili** [comment]
I8N does not seem to scalable. All languages reside in one file. Is there a solution to have a file for each language? 
**Update**

Ok, I think I found a solution. Ill provide a template and a script to join the different languages and will test it.

Could you rename and copy the icons into a folder besides the "icon" folder, so I can make the theme selectable?

**Comment by RedFraction** [comment]
1. Ok, I will move icons set. 
2. And I can redesign my solution, to make it work with amount of files. So it will be a diffrent file for each language.

**Comment by kanehekili** [comment]
Very good. Thanks for your cooperation. I'll adapt the code for icon theme selection

**Comment by RedFraction** [comment]
My custom Internalization support has been removed
New icons now in icons/flaticons

**Comment by kanehekili** [comment]
Why did you remove the language support? Well I might work on it later.. Merging.

**Comment by RedFraction** [comment]
@kanehekili, Sorry, it's my misunderstanding. Can you contact me to decide on the next steps? All code for i18n remained in my local repository. All contact information you can find on my profile.

**Comment by RedFraction** [comment]
I will impore my i18n solution, and will make new pull request later

**Comment by kanehekili** [comment]
Sorry I didn't react. I have currently some other projects to attend. You i8n changes are still visible, so no harm is done. Could you explain how you created the entries in the code? Did you use some tools or was that done manually?

**Comment by RedFraction** [comment]
Use only standard libs/modules - locale and json, all code and algorithms, created by my self. Inspired by Android developer kit and things like Java XML/JSON XPath libraries like Jackson.

**Comment by kanehekili** [comment]
I still do not understand how to detect and convert all the string occurrences using I8N. Reading [this article](https://lokalise.com/blog/beginners-guide-to-python-i18n/) , it depends on gettext. So if you do not use gettext, how do you identify the text within the code and convert it?

**Comment by RedFraction** [comment]
> I still do not understand how to detect and convert all the string occurrences using I8N. Reading [this article](https://lokalise.com/blog/beginners-guide-to-python-i18n/) , it depends on gettext. So if you do not use gettext, how do you identify the text within the code and convert it?
> 

There is no way, for any "magic" solution that will do all work by pressing big red button. Only with pre-processing software that will run before we started main func or like I do (check next [Pull Request](https://github.com/kanehekili/VideoCut/pull/25)) (all of software that I know - using exact that way). I don't know python as good, as I know java, but if it have some type of annotations, we can use theirs to mark strings and any translation software to do this work, but of course it's require internet access to one of API.

**Pull request merged**
